### ISSUE TITLE
Mac Desktop Client: Cannot paste password

### ISSUE THREAD

**Issue by AYapejian** [wavesplatform/WavesGUI#454]
MacOS: 10.12.6
Client Version: [1.0.0-beta 10](https://s3.ca-central-1.amazonaws.com/wavesdb.com/WavesClient-1.0.0-beta.10-mac.dmg)

I have really long passwords that would be a total pain to type out every time I want to launch the desktop client, currently pasting does not work (nothing happens, no error).  This was during the restore account process on first open of the beta desktop client.  

I quit and decided to not proceed currently so I can't comment if this issue persists after initial restore or not.  Much less of an issue but this is also the case with the seed phrase during restore account.

**Comment by iamunick** [comment]
I confirm the issue.

Also happens (CMD+v and right click, both not responding) when trying to paste a waves address for sending tokens. 

Scanning a QR code doesn't seem to work for me either

**Comment by xenohunter** [comment]
Hello and thanks for reporting! We have fixed it and are planning to release that on Monday.
Fixed in https://github.com/wavesplatform/WavesGUI/pull/469.

**Comment by AYapejian** [comment]
@xenohunter thanks, looks like it's working for me when building beta off master, appreciate it.

**Comment by Hl2run** [comment]
I am running beta v10 and I still cannot copy and paste anything. Passwords, addresses are the most frustrating :(
